export const events_data = [
  {
    instance_id: 9890,
    document_id: 42746,
    name: "Priliminary Pricing Suppliment-2022 - 05 - MM - 6y SPX SUNs (Test) TEST [0000].pdf",
    event: "document.create",
    event_name: "document.create",
  },
  {
    instance_id: 9890,
    name: "Priliminary Pricing Suppliment-2022 - 05 - MM - 6y SPX SUNs (Test) TEST [0000].pdf",
    event: "instance.step-failed",
    event_name: "instance.step-failed",
  },
  {
    instance_id: 9890,
    event: "instance.progress-change",
    event_name: "instance.progress-change",
  },
  {
    instance_id: 9890,
    event: "instance.create",
    event_name: "instance.create",
  },
  {
    instance_id: 9890,
    comment: "Priliminary Pricing random comment...",
    event: "comment.create",
    event_name: "comment.create",
  },
  { instance_id: 9890, event: "task.update", event_name: "task.update" },
  { instance_id: 9890, event: "task.delete", event_name: "task.delete" },
  { instance_id: 9890, event: "task.create", event_name: "task.create" },
  {
    instance_id: 9890,
    document_id: 42111,
    name: "Priliminary Pricing Suppliment-2022 - 05 - MM - 6y SPX SUNs (Test) TEST [0000].pdf",
    event: "instance.completed",
    event_name: "instance.completed",
  },
  {
    instance_id: 1111,
    document_id: 42111,
    name: "Priliminary Pricing Suppliment-2022 - 05 - MM - 6y SPX SUNs (Test) TEST [0000].pdf",
    event: "document.create",
    event_name: "document.create",
  },
  {
    instance_id: 1111,
    name: "Priliminary Pricing Suppliment-2022 - 05 - MM - 6y SPX SUNs (Test) TEST [0000].pdf",
    event: "instance.step-failed",
    event_name: "instance.step-failed",
  },
  {
    instance_id: 1111,
    event: "instance.progress-change",
    event_name: "instance.progress-change",
  },
  {
    instance_id: 1111,
    event: "instance.create",
    event_name: "instance.create",
  },
  {
    instance_id: 1111,
    comment: "Priliminary Pricing random comment...",
    event: "comment.create",
    event_name: "comment.create",
  },
  { instance_id: 1111, event: "task.update", event_name: "task.update" },
  { instance_id: 1111, event: "task.delete", event_name: "task.delete" },
  { instance_id: 1111, event: "task.create", event_name: "task.create" },
  {
    instance_id: 1111,
    document_id: 42746,
    name: "Priliminary Pricing Suppliment-2022 - 05 - MM - 6y SPX SUNs (Test) TEST [0000].pdf",
    event: "instance.completed",
    event_name: "instance.completed",
  },
];
